spring.application.name=finance-manager-backend

# Secret key
app.secret-key=${SECRET_KEY}

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/financemanager?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring AI / Grok (xAI) Configuration
spring.ai.openai.api-key=${GROK_API_KEY}
spring.ai.openai.base-url=https://api.x.ai
spring.ai.openai.chat.options.model=grok-2-latest

# Spring Boot Actuator / Monitoring Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Server Port
server.port=8085
